#!/bin/bash

source ../libs/bash_color

function vidiff()
{
    tmp=$1
    orig=$2
    file=$3

    [ -z $tmp ] && vidiff_usage && exit 0
    [ -z $orig ] && vidiff_usage && exit 0
    [ -z $tmp/$file ] && vidiff_usage && exit 0
    [ -z $orig/$file ] && vidiff_usage && exit 0

    vimdiff $orig/$file $tmp/$file
}

function vidiff_usage ()
{
    echo -e "${COLOR226}vidiff usage: vidiff  path_tmp  path_orig  file_to_compare${COLORNONE}"
}

vidiff
