#!/bin/bash

# BASHRC MODULE - ALIASSES - STD

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# std aliases
alias ll='ls -lhF --color=auto'
alias lla='ls -alhF --color=auto'
alias la='ls -Ah --color=auto'
alias l='ls -CFh --color=auto'
alias cd..='cd ..'
alias du='du -h'
alias df='df -h'

# vim aliases
alias :wq='echo Je ne suis PAS vim'
alias :w='echo Je ne suis PAS vim'
alias :q!='echo Je ne suis PAS vim'
alias vi='vim'
alias gvi='gvim'

# spécail aliases
alias open='gnome-open'
alias rezo="sudo watch netstat -alpe --ip"
alias h='history'
alias j='jobs -l'

alias diff="diff -NEwabur -x *~ -x *.orig -x *.rej -x *.swp"


export VIMPAGER=~/my_scripts/vimpager
alias vless=$VIMPAGER

alias lo='libreoffice'
alias rgrep='grep -HnrIs'
