#!/bin/bash

function set_path_std () {
    PATH_STD=
    PATH_STD=$PATH_STD:/usr/local/bin/
    PATH_STD=$PATH_STD:/usr/local/sbin/
    PATH_STD=$PATH_STD:/usr/bin
    PATH_STD=$PATH_STD:/usr/sbin
    PATH_STD=$PATH_STD:/bin
    PATH_STD=$PATH_STD:/sbin

    export PATH_STD
}


function set_path_own () {
    PATH_OWN=
    PATH_OWN=${PATH_OWN}:$HOME/bin
    PATH_OWN=${PATH_OWN}:$HOME/scripts/bin

    export PATH_OWN
}


function set_ld_library_path_std () {
    LD_LIBRARY_PATH_STD=
    LD_LIBRARY_PATH_STD=${LD_LIBRARY_PATH_STD}:/usr/local/lib/
    LD_LIBRARY_PATH_STD=${LD_LIBRARY_PATH_STD}:/usr/local/lib64/
    LD_LIBRARY_PATH_STD=${LD_LIBRARY_PATH_STD}:/usr/lib/
    LD_LIBRARY_PATH_STD=${LD_LIBRARY_PATH_STD}:/usr/lib64/
    LD_LIBRARY_PATH_STD=${LD_LIBRARY_PATH_STD}:/lib/
    LD_LIBRARY_PATH_STD=${LD_LIBRARY_PATH_STD}:/lib64/

    export LD_LIBRARY_PATH_STD
}


function set_ld_library_path_own () {
    LD_LIBRARY_PATH_OWN=

    export LD_LIBRARY_PATH_OWN
}


function set_pkg_config_std () {
    PKG_CONFIG_PATH_STD=
    PKG_CONFIG_PATH_STD=/usr/lib/pkgconfig
    export PKG_CONFIG_STD
}


function set_pkg_config_own () {
    PKG_CONFIG_PATH_OWN=

    export PKG_CONFIG_OWN
}

function set_own_env () {
    CTAGS_DIRECTORY=$HOME/.vim/tags
}

function set_std () {
    set_path_std
    set_ld_library_path_std
    set_pkg_config_std
}


function set_own () {
    set_path_own
    set_ld_library_path_own
    set_pkg_config_own
}

